Repository ThugMS/VR_CPR_Project, pull requests merged in 2022-05, with the labels that each got.

#1 minseok branch push
  Assets/Scenes/SampleScene.unity
  UserSettings/Layouts/default-2021.dwlt
Labels: minseok, feat

#2 사람 손 포팅
  .vsconfig
  Assets/Animation.meta
  Assets/Animation/Close.anim
  Assets/Animation/Close.anim.meta
  Assets/Animation/Grip.mask
  Assets/Animation/Grip.mask.meta
  Assets/Animation/HandAnimator.controller
  Assets/Animation/HandAnimator.controller.meta
  Assets/Animation/Trigger.mask
  Assets/Animation/Trigger.mask.meta
  Assets/Ground.controller
  Assets/Ground.controller.meta
  Assets/LeftHand.controller
  Assets/LeftHand.controller.meta
  Assets/Models.meta
  Assets/Models/LeftHand.fbx
  Assets/Models/LeftHand.fbx.meta
  Assets/Scenes/SampleScene.unity
  Assets/Scripts.meta
  Assets/Scripts/Hand.cs
  Assets/Scripts/Hand.cs.meta
  Assets/Scripts/HandController.cs
  Assets/Scripts/HandController.cs.meta
  ProjectSettings/ProjectSettings.asset
  UserSettings/Layouts/default-2021.dwlt
Labels: jaehyeong, feat

#3 [feat] 기본적인 맵 구성을 추가했습니다.
  Assets/Scenes/SampleScene.unity
  Packages/manifest.json
  Packages/packages-lock.json
  ProjectSettings/ProjectSettings.asset
  UserSettings/EditorUserSettings.asset
  UserSettings/Layouts/default-2021.dwlt
Labels: minseok, feat

#6 [feat] 유저의 시작위치를 손보고 전체적인 크기 비율을 맞췄습니다.
  Assets/Scenes/SampleScene.unity
  UserSettings/EditorUserSettings.asset
  UserSettings/Layouts/default-2021.dwlt
Labels: minseok, fix

#11 [fix] Asset일부가 안나오는 오류를 수정했습니다.
  Assets/Scenes/SampleScene.unity
  UserSettings/Layouts/default-2021.dwlt
Labels: minseok, fix

#24 [feat] 클리커 추가
  Assets/Materials/GroundMat.mat
  Assets/Materials/GroundMat.mat.meta
  Assets/Materials/TemptClicker.mat
  Assets/Materials/TemptClicker.mat.meta
  Assets/Materials/TemptPrestal.mat
  Assets/Materials/TemptPrestal.mat.meta
  Assets/Scenes/SampleScene.unity
  Assets/Scripts/PhsicsButton.cs
  Assets/Scripts/PhsicsButton.cs.meta
Labels: jaehyeong, feat
