Repository ThugMS/VR_CPR_Project, pull requests merged in 2022-06, with the labels that each got.

#28 [feat] 조이스틱과 핸드트래킹 구현
  Assets/Scenes/SampleScene.unity
  Assets/XR/Settings/OpenXR Package Settings.asset
  Assets/XR/XRGeneralSettings.asset
  Packages/manifest.json
  Packages/packages-lock.json
  ProjectSettings/ProjectSettings.asset
  UserSettings/EditorUserSettings.asset
  UserSettings/Layouts/default-2021.dwlt
Labels: minseok, feat

#30 [feat] 컨트롤러와 핸드 트래킹에서의 물체와의 상호작용을 추가했습니다.
  Assets/Scenes/SampleScene.unity
  Assets/Scenes/test1.unity
  Assets/XR/Settings/OpenXR Package Settings.asset
  UserSettings/EditorUserSettings.asset
  UserSettings/Layouts/default-2021.dwlt
Labels: minseok, feat

#32 [feat] 핸드트래킹 수정부분이 있고 버튼을 구현하였습니다.
  Assets/Scenes/SampleScene.unity
  ProjectSettings/QualitySettings.asset
  ProjectSettings/TagManager.asset
  UserSettings/EditorUserSettings.asset
  UserSettings/Layouts/default-2021.dwlt
Labels: minseok, feat, fix

#34 [feat] ButtonVR Script file
  Assets/Scripts/ButtonVR.cs
  Assets/Scripts/ButtonVR.cs.meta
Labels: minseok, feat

#41 [feat] 시작 이후 카메라 이동 및 퀴즈룸 생성
  Assets/Pretab.meta
  Assets/Pretab/Area Light (4).prefab
  Assets/Pretab/Area Light (4).prefab.meta
  Assets/Pretab/CameraCanvas1.prefab
  Assets/Pretab/CameraCanvas1.prefab.meta
  Assets/Pretab/Quiz Room.prefab
  Assets/Pretab/Quiz Room.prefab.meta
  Assets/Pretab/QuizCanvas.prefab
  Assets/Pretab/QuizCanvas.prefab.meta
  Assets/Pretab/StartCanvas.prefab
  Assets/Pretab/StartCanvas.prefab.meta
  Assets/Pretab/Wall.prefab
  Assets/Pretab/Wall.prefab.meta
  Assets/Scenes/test1 pjh.unity
  Assets/Scenes/test1 pjh.unity.meta
  Assets/Scripts/MoveCamera.cs
  Assets/Scripts/MoveCamera.cs.meta
  Assets/Scripts/QuizEvent.cs
  Assets/Scripts/QuizEvent.cs.meta
  Assets/Scripts/StartButtonPush.cs
  Assets/Scripts/StartButtonPush.cs.meta
  Assets/Scripts/StartToggleCheck.cs
  Assets/Scripts/StartToggleCheck.cs.meta
Labels: jaehyeong, feat
